all:
	vulcanize --inline basics.html -o build/basics.html
	vulcanize --config exclude-basics.json codemirror.html -o build/codemirror.html
	vulcanize --config exclude-basics.json layout2.html -o build/layout2.html
	vulcanize --config exclude-basics.json icons.html -o build/icons.html
	vulcanize --config exclude-basics.json widgets.html -o build/widgets.html
	vulcanize --config exclude-basics.json interact.html -o build/interact.html
	vulcanize --config exclude-basics.json latex.html -o build/latex.html
